### ISSUE TITLE
Feature -- Remind.py

### ISSUE THREAD

**Issue by wolfy852** [lrstanley/Code#27]
Code displays `IndexError: list index out of range (file "/usr/local/bin/Code/modules/tell.py, line 112, in time_diff)` after leaving notes directed at yourself.

Result in SSH terminal:

```
     [ERROR] | Traceback (most recent call last):
     [ERROR] |   File "/usr/local/bin/Code/core/bot.py", line 326, in call
     [ERROR] |     func(code, input)
     [ERROR] |   File "/usr/local/bin/Code/modules/tell.py", line 96, in tell_trigger
     [ERROR] |     tmp = template % (time_diff(entry['time']), entry['sender'], entry['msg'])
     [ERROR] |   File "/usr/local/bin/Code/modules/tell.py", line 112, in time_diff
     [ERROR] |     return tools.relative(seconds=int(curr - int(checked)))[0] + ' ago'
     [ERROR] | IndexError: list index out of range
```

In order to reproduce, simply leave a note for your own nick.

**Comment by lrstanley** [comment]
This repository has been archived, either due to lack of time or no maintainers. If you are wondering why, please see "A note on archived repositories" documented on my [profile](https://github.com/lrstanley). If this repository is un-archived in the future, this issue may be re-opened.
