### ISSUE TITLE
Feature - Tempban command/options

### ISSUE THREAD

**Issue by phroa** [lrstanley/Code#35]
Ideally, both in the form of a `.tempban` command, and an option to make all `.ban`s expire after a configurable delay, say, 2 hours.

I'm thinking something along the lines of `.tempban <mask> 1y2m3w4d5h <(kick)reason>`. Or whatever.

Cheers,  
-_phroa_

**Comment by lrstanley** [comment]
This repository has been archived, either due to lack of time or no maintainers. If you are wondering why, please see "A note on archived repositories" documented on my [profile](https://github.com/lrstanley). If this repository is un-archived in the future, this issue may be re-opened.
