### ISSUE TITLE
steam.py -- make use of new found API

### ISSUE THREAD

**Issue by lrstanley** [lrstanley/Code#86]
[Use this](https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI)

Too lazy to do it right now, making a feature request.

**Comment by Liamraystanley** [comment]
Also fix html attributes in game titles (test with gmod)

**Comment by lukeroge** [comment]
This API is solid. Been using it for quite a while in my project, but it does often have performance issues (it's a bit slow)

**Comment by lrstanley** [comment]
This repository has been archived, either due to lack of time or no maintainers. If you are wondering why, please see "A note on archived repositories" documented on my [profile](https://github.com/lrstanley). If this repository is un-archived in the future, this issue may be re-opened.
