### ISSUE TITLE
.steam fails to fetch user info

### ISSUE THREAD

**Issue by FM1337** [lrstanley/Code#91]
.steam no longer fetches user info successfully

**Comment by Liamraystanley** [comment]
This looks like it's related to Cloudflare on their site, and is currently nothing that I can fix.

**Comment by FM1337** [comment]
Suggestion;

Use https://github.com/Anorov/cloudflare-scrape to get past cloudflare.

**Comment by lukeroge** [comment]
As said on the first issue and this one by FM1337, cfscrape/cloudflarescrape is indeed a working solution, but it requires a javascript engine to be installed which is a rather big ask. Also, you'll need the one from the git link above, the `cfscrape-fork` version on PIP does not work anymore :(
